name = "Snorpcraft 26.1.2"
author = "Snorps"
version = "33"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "244789f4eab1ae9c7c075eb9bfceee98f6864a547ca03bb9ca8492db3d2dd8db"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
