name = "Snorpcraft 26.1.2"
author = "Snorps"
version = "30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a5a3be6989a779ee7d545ed58c0700b6c23a62037d3979fa5396b72f54d07ab"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
