name = "Snorpcraft 26.1.2"
author = "Snorps"
version = "31"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a278c7da476455dddee25b26e8f2e9c8ab4dc21da692234fb7a3734c2374725"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
